Fix failed CI job
```
Run pnpm publish
 ERR_PNPM_GIT_UNKNOWN_BRANCH  The Git HEAD may not attached to any branch, but your "publish-branch" is set to "master|main".

If you want to disable Git checks on publish, set the "git-checks" setting to "false", or run again with "--no-git-checks".
Error: Process completed with exit code 1.
```

See <https://github.com/GrottoPress/kitty/actions/runs/17502925118/job/49720121416>.